'use client';

import { useState } from 'react';

export default function ActivateLicensePage() {
  const [requestKey, setRequestKey] = useState('');
  const [licenseKey, setLicenseKey] = useState('');
  const [message, setMessage] = useState('');

  const generateLicense = async () => {
    if (!requestKey.trim()) {
      setMessage('Please paste a valid request key.');
      return;
    }

    const res = await fetch('/api/generate-license', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ requestKey }),
    });

    const data = await res.json();

    if (!res.ok) {
      setMessage(data.error || 'Failed to generate license.');
      return;
    }

    setLicenseKey(data.license);
    setMessage('License generated successfully.');
  };

  return (
    <div className="max-w-4xl mx-auto">
      <h1 className="text-4xl font-bold text-teal-900 mb-10">Activate License</h1>

      <div className="bg-white shadow-lg rounded-2xl p-8 border border-teal-100 space-y-6">

        <div>
          <label className="font-semibold">Paste Request Key</label>
          <textarea
            className="w-full border border-gray-300 rounded-lg px-4 py-3 mt-2"
            rows={4}
            value={requestKey}
            onChange={(e) => setRequestKey(e.target.value)}
            placeholder="Paste the request key generated by your installed app..."
          />
        </div>

        <button
          onClick={generateLicense}
          className="bg-teal-600 text-white px-6 py-3 rounded-lg hover:bg-teal-700"
        >
          Generate License Key
        </button>

        {message && <p className="text-green-700">{message}</p>}

        {licenseKey && (
          <div>
            <label className="font-semibold">Your License Key</label>
            <div className="flex items-center gap-3 mt-2">
              <input
                type="text"
                readOnly
                value={licenseKey}
                className="border border-gray-300 rounded-lg px-4 py-2 w-full bg-gray-50"
              />
              <button
                onClick={() => navigator.clipboard.writeText(licenseKey)}
                className="bg-teal-600 text-white px-4 py-2 rounded-lg hover:bg-teal-700"
              >
                Copy
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
