"use client";

import { useState } from "react";
import { supabaseBrowser } from "@/lib/supabase/client";

const PRODUCT_PLANS = [
  "CentralCore Pro",
  "CentralCore",
  "Pro",
];

export default function ClientLicenseRequestPage() {
  const supabase = supabaseBrowser();
  const [requestKey, setRequestKey] = useState("");
  const [notes, setNotes] = useState("");
  const [productName, setProductName] = useState("");
  const [saving, setSaving] = useState(false);
  const [msg, setMsg] = useState<null | { type: "error" | "success"; text: string }>(null);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setMsg(null);

    if (!requestKey.trim()) {
      setMsg({ type: "error", text: "Please paste your License Request Key." });
      return;
    }

    if (!productName) {
      setMsg({ type: "error", text: "Please select a Product Plan." });
      return;
    }

    setSaving(true);

    const {
      data: { session },
    } = await supabase.auth.getSession();

    if (!session) {
      setMsg({ type: "error", text: "You must be logged in." });
      setSaving(false);
      return;
    }

    const { error } = await supabase.from("LicenseRequest").insert({
      id: crypto.randomUUID(),
      userId: session.user.id,
      requestKey: requestKey.trim(),
      productName,
      notes: notes || null,
      status: "PENDING",
      userEmail: session.user.email ?? null,
    });

    if (error) {
      console.error("LicenseRequest insert error:", error);
      setMsg({ type: "error", text: "Failed to send license request." });
      setSaving(false);
      return;
    }

    setMsg({ type: "success", text: "License request sent successfully." });
    setRequestKey("");
    setNotes("");
    setProductName("");
    setSaving(false);
  }

  return (
    <div>
      <h1 className="text-xl font-bold mb-4">Send License Request Key</h1>

      <form
        onSubmit={handleSubmit}
        className="bg-white rounded shadow p-4 max-w-xl space-y-4"
      >
        <div>
          <label className="block mb-2 font-semibold">Product Plan</label>
          <select
            className="w-full p-2 border rounded"
            value={productName}
            onChange={(e) => setProductName(e.target.value)}
          >
            <option value="">Select a product plan...</option>
            {PRODUCT_PLANS.map((p) => (
              <option key={p} value={p}>
                {p}
              </option>
            ))}
          </select>
        </div>

        <div>
          <label className="block mb-2 font-semibold">
            License Request Key (from your machine)
          </label>
          <textarea
            className="w-full p-3 border rounded"
            rows={5}
            value={requestKey}
            onChange={(e) => setRequestKey(e.target.value)}
            placeholder="Paste the License Request Key generated by your machine..."
          />
        </div>

        <div>
          <label className="block mb-2 font-semibold">Notes (optional)</label>
          <textarea
            className="w-full p-3 border rounded"
            rows={3}
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Any extra info for admin..."
          />
        </div>

        {msg && (
          <p
            className={`text-sm mb-2 ${
              msg.type === "error" ? "text-red-600" : "text-green-600"
            }`}
          >
            {msg.text}
          </p>
        )}

        <button
          type="submit"
          disabled={saving}
          className="px-4 py-2 bg-emerald-600 text-white rounded hover:bg-emerald-700 disabled:opacity-50"
        >
          {saving ? "Sending..." : "Send Request"}
        </button>
      </form>
    </div>
  );
}
