"use client";

import { useEffect, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase/client";

const PRODUCT_PLANS = ["Starter", "Pro", "Enterprise"];

export default function ClientLicenseRequestPage() {
  const supabase = supabaseBrowser();

  const [requestKey, setRequestKey] = useState("");
  const [notes, setNotes] = useState("");
  const [productName, setProductName] = useState("");

  const [companyName, setCompanyName] = useState("");
  const [userEmail, setUserEmail] = useState("");

  const [saving, setSaving] = useState(false);
  const [msg, setMsg] = useState<null | { type: "error" | "success"; text: string }>(null);

  // AUTO‑LOAD EMAIL + COMPANY NAME
  useEffect(() => {
    async function loadUserInfo() {
      const {
        data: { session },
      } = await supabase.auth.getSession();

      if (!session) return;

      // Auto-fill email
      setUserEmail(session.user.email ?? "");

      const userId = session.user.id;

      // Load company membership
      const { data: membership } = await supabase
        .from("user_companies")
        .select("company_id")
        .eq("user_id", userId)
        .maybeSingle();

      if (!membership?.company_id) {
        console.log("No company_id found for user in user_companies");
        return;
      }

      // Load company name
      const { data: company } = await supabase
        .from("companies")
        .select("name")
        .eq("id", membership.company_id)
        .maybeSingle();

      setCompanyName(company?.name ?? "");
    }

    loadUserInfo();
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setMsg(null);

    if (!productName) {
      setMsg({ type: "error", text: "Please select a Product Plan." });
      return;
    }

    if (!requestKey.trim()) {
      setMsg({ type: "error", text: "Please paste your License Request Key." });
      return;
    }

    if (!companyName.trim()) {
      setMsg({ type: "error", text: "Company name missing." });
      return;
    }

    if (!userEmail.trim()) {
      setMsg({ type: "error", text: "Email missing." });
      return;
    }

    setSaving(true);

    const {
      data: { session },
    } = await supabase.auth.getSession();

    if (!session) {
      setMsg({ type: "error", text: "You must be logged in." });
      setSaving(false);
      return;
    }

    const userId = session.user.id;

    // ⭐ FIXED: Correct API endpoint for Client Portal
    const res = await fetch("/api/client/license-requests", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        userId,
        userEmail,
        companyName,
        productName,
        requestKey: requestKey.trim(),
        notes: notes || null,
      }),
    });

    const data = await res.json();

    if (!res.ok) {
      setMsg({ type: "error", text: data.error || "Failed to send license request." });
      setSaving(false);
      return;
    }

    setMsg({ type: "success", text: "License request sent successfully." });
    setRequestKey("");
    setNotes("");
    setProductName("");
    setSaving(false);
  }

  return (
    <div>
      <h1 className="text-xl font-bold mb-4">Send License Request Key</h1>

      <form
        onSubmit={handleSubmit}
        className="bg-white rounded shadow p-4 max-w-xl space-y-4"
      >
        {/* AUTO‑FILLED EMAIL */}
        <div>
          <label className="block mb-2 font-semibold">Your Email</label>
          <input
            type="text"
            className="w-full p-2 border rounded bg-gray-100"
            value={userEmail}
            readOnly
          />
        </div>

        {/* AUTO‑FILLED COMPANY NAME */}
        <div>
          <label className="block mb-2 font-semibold">Company Name</label>
          <input
            type="text"
            className="w-full p-2 border rounded bg-gray-100"
            value={companyName}
            readOnly
          />
        </div>

        <div>
          <label className="block mb-2 font-semibold">Product Plan</label>
          <select
            className="w-full p-2 border rounded"
            value={productName}
            onChange={(e) => setProductName(e.target.value)}
          >
            <option value="">Select a product plan...</option>
            {PRODUCT_PLANS.map((p) => (
              <option key={p} value={p}>
                {p}
              </option>
            ))}
          </select>
        </div>

        <div>
          <label className="block mb-2 font-semibold">
            License Request Key (from your machine)
          </label>
          <textarea
            className="w-full p-3 border rounded"
            rows={5}
            value={requestKey}
            onChange={(e) => setRequestKey(e.target.value)}
            placeholder="Paste the License Request Key generated by your machine..."
          />
        </div>

        <div>
          <label className="block mb-2 font-semibold">Notes (optional)</label>
          <textarea
            className="w-full p-3 border rounded"
            rows={3}
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Any extra info for admin..."
          />
        </div>

        {msg && (
          <p
            className={`text-sm mb-2 ${
              msg.type === "error" ? "text-red-600" : "text-green-600"
            }`}
          >
            {msg.text}
          </p>
        )}

        <button
          type="submit"
          disabled={saving}
          className="px-4 py-2 bg-emerald-600 text-white rounded hover:bg-emerald-700 disabled:opacity-50"
        >
          {saving ? "Sending..." : "Send Request"}
        </button>
      </form>
    </div>
  );
}
